;this file for FamiTone2 library generated by text2data tool

FamiTrackerEndSong_music_data:
	.byte 1
	.word @instruments
	.word @samples-3
	.word @song0ch0,@song0ch1,@song0ch2,@song0ch3,@song0ch4,307,256

@instruments:
	.byte $30 ;instrument $00
	.word @env1,@env0,@env0
	.byte $00
	.byte $30 ;instrument $01
	.word @env2,@env0,@env0
	.byte $00
	.byte $30 ;instrument $02
	.word @env3,@env0,@env0
	.byte $00

@samples:
@env0:
	.byte $c0,$00,$00
@env1:
	.byte $cf,$ce,$cd,$cc,$cb,$ca,$c9,$c8,$c7,$c6,$c5,$c4,$c3,$c2,$c1,$c0
	.byte $00,$0f
@env2:
	.byte $cf,$cd,$cb,$c9,$c7,$c5,$c3,$c1,$c0,$00,$08
@env3:
	.byte $cf,$cc,$c9,$c6,$c3,$c0,$00,$05


@song0ch0:
	.byte $fb,$06
@song0ch0loop:
@ref0:
	.byte $80,$59,$59,$5d,$61,$61,$5d,$59,$53,$5d,$61,$63,$5d,$59,$57,$53
	.byte $4f,$53,$57,$59,$5d,$61,$63,$5d,$59,$57,$53,$4f,$4b,$49,$45,$40
	.byte $85
@ref1:
	.byte $61,$61,$63,$67,$67,$63,$61,$59,$53,$57,$5b,$5d,$61,$73,$67,$6b
	.byte $6b,$67,$65,$61,$5d,$5b,$57,$53,$4f,$4d,$49,$45,$43,$3f,$3a,$85
	.byte $fd
	.word @song0ch0loop

@song0ch1:
@song0ch1loop:
@ref2:
	.byte $82,$53,$53,$57,$59,$59,$57,$53,$4b,$4f,$53,$57,$4f,$4b,$49,$45
	.byte $41,$45,$49,$4b,$4f,$53,$57,$4f,$4b,$4f,$4b,$49,$45,$41,$3f,$3a
	.byte $85
@ref3:
	.byte $59,$59,$5d,$61,$61,$5d,$59,$53,$4d,$4f,$53,$57,$5b,$5d,$61,$73
	.byte $65,$61,$5d,$5b,$57,$53,$51,$4d,$49,$45,$43,$3f,$3b,$39,$34,$85
	.byte $fd
	.word @song0ch1loop

@song0ch2:
@song0ch2loop:
@ref4:
	.byte $84,$29,$29,$2d,$31,$31,$2d,$29,$23,$27,$29,$2d,$27,$23,$1f,$1b
	.byte $19,$1b,$1f,$23,$27,$29,$2d,$27,$23,$2d,$29,$27,$23,$1f,$1b,$18
	.byte $85
@ref5:
	.byte $31,$31,$33,$37,$37,$33,$31,$29,$2b,$2d,$31,$35,$37,$3b,$3f,$43
	.byte $43,$3f,$3b,$39,$35,$31,$2d,$2b,$27,$23,$21,$1d,$19,$15,$12,$85
	.byte $fd
	.word @song0ch2loop

@song0ch3:
@song0ch3loop:
@ref6:
	.byte $f9,$85
@ref7:
	.byte $f9,$85
	.byte $fd
	.word @song0ch3loop

@song0ch4:
@song0ch4loop:
@ref8:
	.byte $f9,$85
@ref9:
	.byte $f9,$85
	.byte $fd
	.word @song0ch4loop
