;this file for FamiTone2 library generated by text2data tool

FamiTrackerSongs_music_data:
	.byte 3
	.word @instruments
	.word @samples-3
	.word @song0ch0,@song0ch1,@song0ch2,@song0ch3,@song0ch4,307,256
	.word @song1ch0,@song1ch1,@song1ch2,@song1ch3,@song1ch4,307,256
	.word @song2ch0,@song2ch1,@song2ch2,@song2ch3,@song2ch4,307,256

@instruments:
	.byte $30 ;instrument $00
	.word @env1,@env0,@env0
	.byte $00
	.byte $30 ;instrument $01
	.word @env2,@env0,@env0
	.byte $00
	.byte $30 ;instrument $02
	.word @env3,@env0,@env0
	.byte $00
	.byte $30 ;instrument $03
	.word @env4,@env0,@env0
	.byte $00
	.byte $30 ;instrument $04
	.word @env5,@env0,@env0
	.byte $00
	.byte $30 ;instrument $05
	.word @env6,@env0,@env0
	.byte $00
	.byte $30 ;instrument $06
	.word @env7,@env0,@env0
	.byte $00
	.byte $30 ;instrument $07
	.word @env7,@env0,@env0
	.byte $00

@samples:
@env0:
	.byte $c0,$00,$00
@env1:
	.byte $cf,$ce,$cd,$cc,$cb,$ca,$c9,$c8,$c7,$c6,$c5,$c4,$c3,$c2,$c1,$c0
	.byte $00,$0f
@env2:
	.byte $cf,$cd,$cb,$c9,$c7,$c5,$c3,$c1,$c0,$00,$08
@env3:
	.byte $cf,$cc,$c9,$c6,$c3,$c0,$00,$05
@env4:
	.byte $cf,$cd,$cb,$c9,$c7,$c5,$c3,$c0,$00,$07
@env5:
	.byte $cf,$ca,$c7,$c4,$c2,$c0,$00,$05
@env6:
	.byte $cf,$00,$00
@env7:
	.byte $cf,$cd,$c9,$c5,$c2,$c0,$00,$05


@song0ch0:
	.byte $fb,$06
@song0ch0loop:
@ref0:
	.byte $80,$59,$59,$5d,$61,$61,$5d,$59,$53,$5d,$61,$63,$5d,$59,$57,$53
	.byte $4f,$53,$57,$59,$5d,$61,$63,$5d,$59,$57,$53,$4f,$4b,$49,$45,$40
	.byte $85
@ref1:
	.byte $61,$61,$63,$67,$67,$63,$61,$59,$53,$57,$5b,$5d,$61,$73,$67,$6b
	.byte $6b,$67,$65,$61,$5d,$5b,$57,$53,$4f,$4d,$49,$45,$43,$3f,$3a,$85
	.byte $fd
	.word @song0ch0loop

@song0ch1:
@song0ch1loop:
@ref2:
	.byte $82,$53,$53,$57,$59,$59,$57,$53,$4b,$4f,$53,$57,$4f,$4b,$49,$45
	.byte $41,$45,$49,$4b,$4f,$53,$57,$4f,$4b,$4f,$4b,$49,$45,$41,$3f,$3a
	.byte $85
@ref3:
	.byte $59,$59,$5d,$61,$61,$5d,$59,$53,$4d,$4f,$53,$57,$5b,$5d,$61,$73
	.byte $65,$61,$5d,$5b,$57,$53,$51,$4d,$49,$45,$43,$3f,$3b,$39,$34,$85
	.byte $fd
	.word @song0ch1loop

@song0ch2:
@song0ch2loop:
@ref4:
	.byte $84,$29,$29,$2d,$31,$31,$2d,$29,$23,$27,$29,$2d,$27,$23,$1f,$1b
	.byte $19,$1b,$1f,$23,$27,$29,$2d,$27,$23,$2d,$29,$27,$23,$1f,$1b,$18
	.byte $85
@ref5:
	.byte $31,$31,$33,$37,$37,$33,$31,$29,$2b,$2d,$31,$35,$37,$3b,$3f,$43
	.byte $43,$3f,$3b,$39,$35,$31,$2d,$2b,$27,$23,$21,$1d,$19,$15,$12,$85
	.byte $fd
	.word @song0ch2loop

@song0ch3:
@song0ch3loop:
@ref6:
	.byte $f9,$85
@ref7:
	.byte $f9,$85
	.byte $fd
	.word @song0ch3loop

@song0ch4:
@song0ch4loop:
@ref8:
	.byte $f9,$85
@ref9:
	.byte $f9,$85
	.byte $fd
	.word @song0ch4loop


@song1ch0:
	.byte $fb,$06
@song1ch0loop:
@ref10:
	.byte $86,$32,$9d,$28,$9d,$2e,$9d,$28,$9d
	.byte $fd
	.word @song1ch0loop

@song1ch1:
@song1ch1loop:
@ref11:
	.byte $87,$88,$66,$95,$6a,$95,$6c,$9d,$62,$a5
	.byte $fd
	.word @song1ch1loop

@song1ch2:
@song1ch2loop:
@ref12:
	.byte $8a,$1a,$9d,$10,$9d,$16,$9d,$10,$9d
	.byte $fd
	.word @song1ch2loop

@song1ch3:
@song1ch3loop:
@ref13:
	.byte $f9,$85
	.byte $fd
	.word @song1ch3loop

@song1ch4:
@song1ch4loop:
@ref14:
	.byte $f9,$85
	.byte $fd
	.word @song1ch4loop


@song2ch0:
	.byte $fb,$06
@song2ch0loop:
@ref15:
	.byte $83,$8c,$4a,$85,$4a,$85,$40,$85,$40,$85,$46,$85,$46,$85,$40,$85
	.byte $40,$85,$4e,$85,$4e,$85,$40,$85,$40,$85,$46,$85,$46,$85,$40,$85
	.byte $40,$81
	.byte $fd
	.word @song2ch0loop

@song2ch1:
@song2ch1loop:
@ref16:
	.byte $8e,$6a,$8d,$70,$8d,$7a,$8d,$6c,$8d,$70,$8d,$76,$8d,$70,$8d,$66
	.byte $8d
	.byte $fd
	.word @song2ch1loop

@song2ch2:
@song2ch2loop:
@ref17:
	.byte $8a,$1a,$8d,$1e,$8d,$10,$8d,$14,$8d,$16,$8d,$1a,$8d,$10,$8d,$10
	.byte $8d
	.byte $fd
	.word @song2ch2loop

@song2ch3:
@song2ch3loop:
@ref18:
	.byte $f9,$85
	.byte $fd
	.word @song2ch3loop

@song2ch4:
@song2ch4loop:
@ref19:
	.byte $f9,$85
	.byte $fd
	.word @song2ch4loop
